version: '3.8'
services:

  postgres:
    restart: always
    #  this container_name would be used inside of the pp as hostname for postgres
    container_name: postgres_db
    image: postgres:alpine
    # provide script to initiate tables
    volumes:
      - ./migration/db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    # Pass postgres environment variables
    environment:
      POSTGRES_PASSWORD: zxcvbnml
      POSTGRES_DB: cartdb
      POSTGRES_USER: cartdb_user
    expose:
      - "5432"
    ports:
      - 5432:5432

volumes:
  postgres_data: